### ISSUE TITLE
Reset chapters read.

### ISSUE THREAD

**Issue by Nivad1** [Aidoku/Aidoku#330] opened 2023-08-29 19:22 UTC
I'll read many chapters, and when I take a break and come back it is back at chapter 1.

**Comment by Skittyblock** [comment] 2023-08-31 20:11
you likely were using a source like Asura Scans that changed their ids, which reset your chapters and lost the associated reading history, or you had incognito mode on so your history didn't save. is that the case? is your history tab empty?

**Comment by Nivad1** [comment] 2023-08-31 20:18
I’m not sure the source it’s on many books though. No incognito mode is off I found out that mistake a long time ago. You telling me about the history tab is my first time looking at it honestly. I’m pretty disappointed in myself honestly haha. But it is logged in there fine. Sent from my iPhoneOn Aug 31, 2023, at 4:11 PM, Skitty ***@***.***> wrote:﻿
you likely were using a source like Asura Scans that changed their ids, which reset your chapters and lost the associated reading history, or you had incognito mode on so your history didn't save. is that the case? is your history tab empty?

**Comment by Skittyblock** [comment] 2023-08-31 20:40
I'm gonna close this since it's very likely that it was Asura or some other source changing chapter ids, but if it happens again and you have more information to provide that could help me reproduce or identify the issue, feel free to reopen or create a new issue.

**Closed by Skittyblock** 2023-08-31 20:40 UTC
Labels: invalid
