### ISSUE TITLE
MAL Tracker Status Not Pushed to MAL Database

### ISSUE THREAD

**Issue by Googolplexed06** [Aidoku/Aidoku#375] opened 2023-11-13 00:32 UTC
As the title states, changing the Status field in the MAL tracker is not reflected on the database after closing the tracker tab. Other fields such as Chapters, Volumes, Started Date, Finished Date, and Score all work as expected. The status field does properly pull from the MAL database, as changes made on the MAL site are immediately reflect in Aidoku. 

I do not currently use AniList so I cannot confirm if this is a common issue for all trackers, but I assume it is MAL specific. 

Since other values update correctly, it is likely an issue specific to the Status field. My first assumption was a syntax mistake in the spelling/capitalization of the string from what the API expects for the Status field, but dug through the Tracker code and it appears that the Status field is correctly populated with a string value that the API expects.

**Comment by Skittyblock** [comment] 2023-11-24 17:39
oops this is a duplicate of #355

**Closed by Skittyblock** 2023-11-24 17:39 UTC
Labels: duplicate
