### ISSUE TITLE
Every reading starts from the first chapter

### ISSUE THREAD

**Issue by Stick-of-WuKong** [Aidoku/Aidoku#410] opened 2024-02-19 07:03 UTC
Although there are tagged readings, it will be in the first chapter every time you open the comic, and you will not open the chapter of the last reading

**Comment by Cuixq123** [comment] 2024-02-19 08:35
Me too, when I switch chapters, I go in from the bookshelf every time I start with the first chapter, can I record the last read chapter, or I continue from the chapter I selected

**Comment by Cuixq123** [comment] 2024-02-19 08:42
> Although there are tagged readings, it will be in the first chapter every time you open the comic, and you will not open the chapter of the last reading

In History, select chapters in the upper right corner, and then mark the chapters that have been read before, and the bookshelf seems to automatically arrive at new chapters

**Comment by Skittyblock** [comment] 2024-03-04 09:47
This is intended behavior. The reading button selects the earliest non-read chapter, meaning that even if you have chapters read in the middle it'll show an earlier chapter if you haven't marked it as read yet.

**Closed by Skittyblock** 2024-03-04 09:47 UTC
Labels: wontfix
