### ISSUE TITLE
Bookmarking/Favoriting specific chapters

### ISSUE THREAD

**Issue by GodOfFestivals** [Aidoku/Aidoku#491] opened 2024-11-06 13:33 UTC
When selecting chapters to mark as read or unread, could there also be an option of “favorite/bookmark”? I love going back and rereading my favorite chapters and specific panels. But sometimes they don’t have names, or I haven’t read them in so long it’s hard to remember… It can just add a little icon off to the side (maybe slightly better than the one I did!). It’ll be good to help remember favorite moments. (If you see this and know the ch. I marked you’re awesome)
![image](https://github.com/user-attachments/assets/e905ade4-5f51-4b6d-ad69-3a46f5b501a1)

**Comment by Skittyblock** [comment] 2024-11-08 18:45
duplicate of #317

**Closed by Skittyblock** 2024-11-08 18:45 UTC
Labels: duplicate
