### ISSUE TITLE
Reading mode local setting

### ISSUE THREAD

**Issue by Goharn** [Aidoku/Aidoku#119] opened 2022-11-09 19:17 UTC
It’ll be nice to have reading mode set per item. Instead of it being set for all. 

Like for example, setting webtoon in vertical scroll mode and manga in left to right.

**Comment by h43nz** [comment] 2022-11-29 22:59
This would be really nice, I finde myself constantly switching between the reading modes

**Comment by Skittyblock** [comment] 2023-01-04 00:11
Realized this is a duplicate of #80

**Closed by Skittyblock** 2023-01-04 00:11 UTC
Labels: duplicate
