### ISSUE TITLE
Zooming function for vertical scroll?

### ISSUE THREAD

**Issue by hyun-an** [Aidoku/Aidoku#108] opened 2022-08-29 00:51 UTC
I’m not sure if it exists or if I didn’t look through in the settings enough but I was wondering if you guys can add like a zooming function to aidoku for vertical scroll mode. There is a mode with zoom but that one makes all the pictures skinny and doesn’t zoom in all the way. Basically what tachiyomi and paperback has where you can pinch in the images.``

**Comment by Skittyblock** [comment] 2022-10-15 15:08
Duplicate of #55

**Closed by Skittyblock** 2022-10-15 15:08 UTC
Labels: duplicate
